#!/bin/bash
# Lists all Git clone URLs for repositories belonging to specified GitHub users
# Includes both user repositories and organization repositories the user belongs to
# Usage: github-list-repos <username1> <username2> ...

set -euo pipefail
IFS=$'\n\t'

for user in "$@"; do
	\gh api "users/${user}/repos" --paginate --jq '.[].clone_url'
	for org in $(\gh api "users/${user}/orgs" --paginate --jq '.[].login'); do
		\gh api "orgs/${org}/repos" --paginate --jq '.[].clone_url'
	done
done
