#!/bin/bash
# Opens the URL from the clipboard in the default browser
# Trims whitespace from the clipboard content before opening

set -euo pipefail
IFS=$'\n\t'

/usr/bin/xdg-open "$(/usr/bin/xclip -out -selection clipboard | /bin/sed 's/\s*$//; s/^\s*//;')"
