#!/bin/bash

set -euo pipefail
IFS=$'\n\t'

\python3 -m venv /tmp/dep-tree-env
# shellcheck source=/dev/null
source /tmp/dep-tree-env/bin/activate
\pip install -r requirements.txt
\pipdeptree -fl
deactivate
\rm -rf /tmp/dep-tree-env
