---
name: ShellCheck

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

permissions: {}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
      - name: ShellCheck
        shell: bash
        run: |
          set -euo pipefail
          IFS=$'\n\t'
          shellcheck $(find . -type f -exec grep -e '^#!.*sh$' -l {} \; | grep -v -e '/\.git/')
